# UAT Environment

server.port=8081

spring.datasource.url=jdbc:mysql://uat-server:3306/filedb
spring.datasource.username=uat_user
spring.datasource.password=uat_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

upload.path=D:/uat/uploads
success.path=D:/uat/success
error.path=D:/uat/error